// Generated by CoffeeScript 1.9.2
var bindApply;

bindApply = function(fn, ctx, args) {
  var a, b, c, d, e;
  a = args[0], b = args[1], c = args[2], d = args[3], e = args[4];
  switch (args.length) {
    case 1:
      return fn.bind(ctx, a);
    case 2:
      return fn.bind(ctx, a, b);
    case 3:
      return fn.bind(ctx, a, b, c);
    case 4:
      return fn.bind(ctx, a, b, c, d);
    case 5:
      return fn.bind(ctx, a, b, c, d, e);
    default:
      return Function.prototype.bind(fn, [ctx].concat(args));
  }
};

module.exports = {
  bindApply: bindApply
};
